### ISSUE TITLE
Its not work with my blog

### ISSUE THREAD

**Issue by rebelholic** [ezikill/AndroidWordPressDemo2#1]
Hello,

I have a problem when testing with [my own json api](http://unity3dindonesia.com/?json=get_recent_posts) just give blank result such as "Description:null". How I can fix it?

My Console Log:

> 08-24 17:45:49.140    6688-6688/wordpress.app.com.androidwordpressdemo I/System.out﹕ http://unity3dindonesia.com/%3Fjson%3Dget_recent_posts

**Comment by ezikill** [comment]
Doesn't work for me either, glad it's not just me then.
